# Numpy

## Numpy
It is a module with a very convenient data type - array

Array characteristics:
1. Fixed size - size predetermined in the creation time
1. Homoigeneity - contains values with one type
1. Memory efficiency
1. Speed efficiency
1. Vectorization - same behaviour as R vectors

## Creation

We will encounter several shared arguments for many numpy functions
1. `shape` - dimensionality of desired array, e.g. 1 x 10, 5 x 5, usually passed as tuple
1. `dtype` - type of data in an array, typically includes specific allocated number of bits per value, e.g. `int`, `float`, `np.int8`, and so on 

In [2]:
import numpy as np

In [3]:
# From python sequence
xs = np.array([1, 2, 3])
xs

array([1, 2, 3])

### `dtype` parameter
`dtype` can be passed with several ways:

1. python type - `int`, `float`
2. string name - `'int'`, `'float'`
3. numpy types - `np.int`, `np.int8`, `np.uint16`, `np.float64`

In [4]:
# Now floats
fractions = np.array([1, 2, 3, 4, 5], dtype='float')
fractions

array([1., 2., 3., 4., 5.])

In [5]:
# Another variant
np.array([1, 2, 3, 4, 5], dtype=float)

array([1., 2., 3., 4., 5.])

In [6]:
# Same
np.array([1, 2, 3, 4, 5], dtype=np.float)

array([1., 2., 3., 4., 5.])

In [7]:
# With specified number of bits per value - 16
floats16 = np.array([1, 2, 3, 4, 5], dtype=np.float16)
floats16

array([1., 2., 3., 4., 5.], dtype=float16)

In [8]:
import sys


# In bytes
sys.getsizeof(fractions)

136

In [9]:
sys.getsizeof(floats16)

106

### Other types of initialization

In [10]:
# Shape is equal to 3 here
# With specific value - 5
np.full(3, 5)

array([5, 5, 5])

In [11]:
# Another shape - 2 x 2
np.full((2, 2), 5)

array([[5, 5],
       [5, 5]])

In [12]:
# Another type
np.full((2, 2), 5, dtype='str')

array([['5', '5'],
       ['5', '5']], dtype='<U1')

### Some edge cases

In [13]:
# All 0
np.zeros(3)

array([0., 0., 0.])

In [14]:
# All 0
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# All ones
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# Identity matrix
# Only for 2-dimensional arrays
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [18]:
# Ranges
np.arange(5)

array([0, 1, 2, 3, 4])

In [19]:
# From 3 to 12
np.arange(3, 12)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
# With step equal to 2
np.arange(3, 12, 2)

array([ 3,  5,  7,  9, 11])

## Vectorization

In [21]:
a = np.arange(3)
b = np.ones(3)
a, b

(array([0, 1, 2]), array([1., 1., 1.]))

In [22]:
a + 3

array([3, 4, 5])

In [23]:
a * 3

array([0, 3, 6])

In [25]:
a + b

array([1., 2., 3.])

In [26]:
a < b

array([ True, False, False])

In [51]:
a * b

array([0., 1., 2.])

In [54]:
# Vector multiplication
a.dot(b)

3.0

In [62]:
a = np.array(((1, 2),
              (3, 4)))

b = np.arange(2)

In [63]:
a + b

array([[1, 3],
       [3, 5]])

In [64]:
a * b

array([[0, 2],
       [0, 4]])

In [65]:
a.dot(b)

array([2, 4])

In [66]:
b.dot(a)

array([3, 4])

In [67]:
a @ b

array([2, 4])

## Useful attributes
1. `shape` - lengths of dimensions, tuple, first rows
1. `size` - number of elements in the array, same as product of `shape`

In [74]:
a.shape

(2, 2)

In [75]:
a.size

4

In [77]:
# Don't use it
len(a)

2

## Indexing
Vast topic. A couple of methods to start with:
1. `a[start:stop:step]` - same as with list, just extended to multiple dimensions
1. `a[[1, 2, 3]]` - "fancy" indexing, will get elements with indices 1, 2 and 3

In [71]:
# Don't pay attention to reshape now, will cover it later
matrix = np.arange(3, 15).reshape(3, -1)
matrix

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [72]:
matrix[0]

array([3, 4, 5, 6])

In [78]:
matrix[-1]

array([11, 12, 13, 14])

In [79]:
matrix[::2]

array([[ 3,  4,  5,  6],
       [11, 12, 13, 14]])

In [80]:
matrix[0, 0]

3

In [81]:
# 1st column
matrix[:, 0]

array([ 3,  7, 11])

In [84]:
matrix[:2, 1:3]

array([[4, 5],
       [8, 9]])

In [85]:
matrix[::2, ::2]

array([[ 3,  5],
       [11, 13]])